# Generated by Django 4.2.7 on 2023-11-12 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Продукт')),
                ('cost', models.DecimalField(decimal_places=7, max_digits=9, verbose_name='Стоимость')),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
