# Generated by Django 4.2.7 on 2023-11-12 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs_api', '0004_alter_cost_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cost',
            name='cost',
        ),
        migrations.AddField(
            model_name='cost',
            name='amount',
            field=models.IntegerField(default=123, verbose_name='Стоимость'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cost',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
    ]
